pub const MAGIC: u8 = 0x56;
pub const VERSION: u8 = 0x01;

pub const COMMAND_TYPE_INIT: u8 = 0x00;
pub const COMMAND_TYPE_LOCK: u8 = 0x01;
pub const COMMAND_TYPE_UNLOCK: u8 = 0x02;
pub const COMMAND_TYPE_PING: u8 = 0x05;

pub const COMMAND_RESULT_SUCCED: u8 = 0x00;
pub const COMMAND_RESULT_UNKNOWN_MAGIC: u8 = 0x01;
pub const COMMAND_RESULT_UNKNOWN_VERSION: u8 = 0x02;
pub const COMMAND_RESULT_UNKNOWN_DB: u8 = 0x03;
pub const COMMAND_RESULT_UNKNOWN_COMMAND: u8 = 0x04;
pub const COMMAND_RESULT_LOCKED_ERROR: u8 = 0x05;
pub const COMMAND_RESULT_UNLOCK_ERROR: u8 = 0x06;
pub const COMMAND_RESULT_UNOWN_ERROR: u8 = 0x07;
pub const COMMAND_RESULT_TIMEOUT: u8 = 0x08;
pub const COMMAND_RESULT_EXPRIED: u8 = 0x09;
pub const COMMAND_RESULT_STATE_ERROR: u8 = 0x0a;
pub const COMMAND_RESULT_ERROR: u8 = 0x0b;
pub const COMMAND_RESULT_LOCK_ACK_WAITING: u8 = 0x0c;

pub const INIT_TYPE_FLAG_HA_CLIENT: u8 = 0x01;
pub const INIT_TYPE_FLAG_IS_TRANSPARENCY: u8 = 0x02;
pub const INIT_TYPE_FLAG_IS_LEADER: u8 = 0x04;
pub const INIT_TYPE_FLAG_HAS_LEADER: u8 = 0x08;
pub const INIT_TYPE_FLAG_IS_SHUTDOWN: u8 = 0x10;

pub const LOCK_FLAG_SHOW_WHEN_LOCKED: u8 = 0x01;
pub const LOCK_FLAG_UPDATE_WHEN_LOCKED: u8 = 0x02;
pub const LOCK_FLAG_FROM_AOF: u8 = 0x04;
pub const LOCK_FLAG_CONCURRENT_CHECK: u8 = 0x08;
pub const LOCK_FLAG_LOCK_TREE_LOCK: u8 = 0x10;
pub const LOCK_FLAG_CONTAINS_DATA: u8 = 0x20;

pub const UNLOCK_FLAG_UNLOCK_FIRST_LOCK_WHEN_UNLOCKED: u8 = 0x01;
pub const UNLOCK_FLAG_CANCEL_WAIT_LOCK_WHEN_UNLOCKED: u8 = 0x02;
pub const UNLOCK_FLAG_FROM_AOF: u8 = 0x04;
pub const UNLOCK_FLAG_SUCCED_TO_LOCK_WAIT: u8 = 0x08;
pub const UNLOCK_FLAG_UNLOCK_TREE_LOCK: u8 = 0x10;
pub const UNLOCK_FLAG_CONTAINS_DATA: u8 = 0x20;

pub const TIMEOUT_FLAG_TIMEOUT_WHEN_CONTAINS_DATA: u16 = 0x0008;
pub const TIMEOUT_FLAG_RCOUNT_IS_PRIORITY: u16 = 0x0010;
pub const TIMEOUT_FLAG_PUSH_SUBSCRIBE: u16 = 0x0020;
pub const TIMEOUT_FLAG_MINUTE_TIME: u16 = 0x0040;
pub const TIMEOUT_FLAG_REVERSE_KEY_LOCK_WHEN_TIMEOUT: u16 = 0x0080;
pub const TIMEOUT_FLAG_UNRENEW_EXPRIED_TIME_WHEN_TIMEOUT: u16 = 0x0100;
pub const TIMEOUT_FLAG_LOCK_WAIT_WHEN_UNLOCK: u16 = 0x0200;
pub const TIMEOUT_FLAG_MILLISECOND_TIME: u16 = 0x0400;
pub const TIMEOUT_FLAG_LOG_ERROR_WHEN_TIMEOUT: u16 = 0x0800;
pub const TIMEOUT_FLAG_REQUIRE_ACKED: u16 = 0x1000;
pub const TIMEOUT_FLAG_UPDATE_NO_RESET_TIMEOUT_CHECKED_COUNT: u16 = 0x2000;
pub const TIMEOUT_FLAG_LESS_LOCK_VERSION_IS_LOCK_SUCCED: u16 = 0x4000;
pub const TIMEOUT_FLAG_KEEPLIVED: u16 = 0x8000;

pub const EXPRIED_FLAG_PUSH_SUBSCRIBE: u16 = 0x0020;
pub const EXPRIED_FLAG_MINUTE_TIME: u16 = 0x0040;
pub const EXPRIED_FLAG_REVERSE_KEY_LOCK_WHEN_EXPRIED: u16 = 0x0080;
pub const EXPRIED_FLAG_ZEOR_AOF_TIME: u16 = 0x0100;
pub const EXPRIED_FLAG_UNLIMITED_AOF_TIME: u16 = 0x0200;
pub const EXPRIED_FLAG_MILLISECOND_TIME: u16 = 0x0400;
pub const EXPRIED_FLAG_LOG_ERROR_WHEN_EXPRIED: u16 = 0x0800;
pub const EXPRIED_FLAG_AOF_TIME_OF_EXPRIED_PARCENT: u16 = 0x1000;
pub const EXPRIED_FLAG_UPDATE_NO_RESET_EXPRIED_CHECKED_COUNT: u16 = 0x2000;
pub const EXPRIED_FLAG_UNLIMITED_EXPRIED_TIME: u16 = 0x4000;
pub const EXPRIED_FLAG_KEEPLIVED: u16 = 0x8000;

pub const LOCK_DATA_STAGE_CURRENT: u8 = 0;
pub const LOCK_DATA_STAGE_UNLOCK: u8 = 1;
pub const LOCK_DATA_STAGE_TIMEOUT: u8 = 2;
pub const LOCK_DATA_STAGE_EXPRIED: u8 = 3;

pub const LOCK_DATA_COMMAND_TYPE_SET: u8 = 0;
pub const LOCK_DATA_COMMAND_TYPE_UNSET: u8 = 1;
pub const LOCK_DATA_COMMAND_TYPE_INCR: u8 = 2;
pub const LOCK_DATA_COMMAND_TYPE_APPEND: u8 = 3;
pub const LOCK_DATA_COMMAND_TYPE_SHIFT: u8 = 4;
pub const LOCK_DATA_COMMAND_TYPE_EXECUTE: u8 = 5;
pub const LOCK_DATA_COMMAND_TYPE_PIPELINE: u8 = 6;
pub const LOCK_DATA_COMMAND_TYPE_PUSH: u8 = 7;
pub const LOCK_DATA_COMMAND_TYPE_POP: u8 = 8;

pub const LOCK_DATA_FLAG_VALUE_TYPE_NUMBER: u8 = 0x01;
pub const LOCK_DATA_FLAG_VALUE_TYPE_ARRAY: u8 = 0x02;
pub const LOCK_DATA_FLAG_VALUE_TYPE_KV: u8 = 0x04;
pub const LOCK_DATA_FLAG_CONTAINS_PROPERTY: u8 = 0x10;
pub const LOCK_DATA_FLAG_PROCESS_FIRST_OR_LAST: u8 = 0x20;
